### ISSUE TITLE
During the day, the blood glows in the dark in dimly lit/pitch black areas.

### ISSUE THREAD

**Issue by Vorimexilo** [CravenCraft/BloodyBits#1]
Self explanatory, this is what it looks like:
![image](https://github.com/user-attachments/assets/e627e78f-6611-4b4c-a766-d0345281a2c1)

**Comment by CravenCraft** [comment]
Just fixed this with the latest release. Check out 1.1.0!

**Comment by Aaokke** [comment]
dont know if youre still working on this, but the same happens in the latest version 1.3.3, downgrading it to 1.3.2 fixes this issue
