### ISSUE TITLE
Changes the blood particle color of certain mobs

### ISSUE THREAD

**Issue by wsxiya** [CravenCraft/BloodyBits#4]
HI, I am using your mod with the physics mod, and I found it works well, but the blood color of the "Creeper" is green, and the death blood color of the physics mod is red. How can I change the blood color of a specific creature to red?

**Comment by wsxiya** [comment]
Uploading freecompress-Base Profile 2024.08.05 - 17.53.06.02.mp4…

**Comment by wsxiya** [comment]
When attacking a creature
![_5K@1YOB}WPQWEDDSS2V}OE](https://github.com/user-attachments/assets/4cdef01a-5c1d-4ec5-8f9f-93bfd56bded7)
When an organism dies
![Uploading R7}F[NS2S3_166BORF1Y18Y.png…]()

**Comment by wsxiya** [comment]
When attacking a creature
![Uploading _5K@1YOB}WPQWEDDSS2V}OE.png…]()

**Comment by wsxiya** [comment]
https://github.com/user-attachments/assets/48783b6d-7049-4c6d-adf0-fa31dd9926f4

**Comment by CravenCraft** [comment]
Hey, just check out the config folder and there should be another folder in there called something like "blood_colors". That'll have a json file in it with multiple entities for certain colors. Just delete the line with the creeper in it

**Comment by wsxiya** [comment]
> 嘿，只需查看配置文件夹，那里应该有另一个文件夹，称为“blood_colors”。其中将有一个 json 文件，其中包含某些颜色的多个实体。只需删除其中包含爬行者的行即可

Thank you, the issue has been resolved
